#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2024 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around tc-rules providing settings for the Cowesett Animal
# Hospital's Cox Cable WAN interface.
#
#
### higher priority stuff
#
# voip - Not currently on it's own vlan, but planning to switch to that if it
# ever becomes trivial.  It looks like our phones are using DSCP: AF31, TOS:
# 0x68 (104 decimal), so I guess we could pick that traffic out.  For now,
# though, I've marked all traffic from our phones' MACs as high priority.
#
### lower priority stuff
#
# anything coming from public WiFi - Marked via iptables
#
### middle tier
#
# anything else, including Shepherd (because it's just a webpage) and DICOM
# from digital xray (because it's basically bulk upload when needed).
#

export DEV=eth0.2
#export UP_MBIT=20
export UP_MBIT=35
#export DOWN_MBIT=100
export DOWN_MBIT=1000

# NOTE: We leave HIGH and LOW alone (at 20% and 5% of the 20Mbit uplink), but
#       we're manually chopping 5M off the guaranteed rate for MEDIUM here to
#       help mitigate the risk of overruns from aragorn/srv-router2, which have
#       their own public IPs and their own tc-rules but share this 20Mbit
#       uplink.
#
export UP_MEDIUM_GUARANTEED_RATE_KBIT=10240

exec $(dirname $0)/tc-rules $*
